In [ ]:
import pandas as pd

In [2]:
atc = pd.read_csv("../data/raw/Distribution of Medicines by ATC.csv")
benzo = pd.read_csv("../data/raw/Benzodiazepines Z Drugs Claims.csv")
trolley = pd.read_csv("../data/raw/Inmo Trolley Data.csv")

In [3]:
print(atc.shape)
print(benzo.shape)
print(trolley.shape)

(11488, 9)
(46120, 9)
(123, 3)

In [5]:
display(atc.info())
display(benzo.info())
display(trolley.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11488 entries, 0 to 11487
Data columns (total 9 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   YEAR_MONTH                                        11488 non-null  int64
 1   ATC Class Category                                11488 non-null  object
 2   ATC Class Code                                    9808 non-null   object
 3   Product Category                                  9808 non-null   object
 4   Prescribing Frequency                             9688 non-null   float64
 5   Prescribing Frequency Percentage of Scheme Total  9688 non-null   float64
 6   Ingredient Cost                                   9688 non-null   float64
 7   Ingredient Cost Percentage of Scheme Total        9688 non-null   float64
 8   Ingredient Cost Percentage of Scheme Total.1      9808 non-null   float64
dtypes: float64(5), int64(1), object(3)
memory usage: 807.9+ KB

None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46120 entries, 0 to 46119
Data columns (total 9 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Region                     46120 non-null  object
 1   Local Health Office (LHO)  46120 non-null  object
 2   YEAR_MONTH                 46120 non-null  int64
 3   ATC Class                  46120 non-null  object
 4   Number of Patients         46120 non-null  int64
 5   Number of Prescriptions    46120 non-null  int64
 6   Prescribing Frequency      46120 non-null  int64
 7   Igredient Cost (€)         46120 non-null  float64
 8   Total Cost (€)             46120 non-null  float64
dtypes: float64(2), int64(4), object(3)
memory usage: 3.2+ MB

None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 123 entries, 0 to 122
Data columns (total 3 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   YEAR_MONTH             123 non-null    int64
 1   Monthly_Trolley_Total  123 non-null    int64
 2   Monthly_Ward_Total     123 non-null    int64
dtypes: int64(3)
memory usage: 3.0 KB

None

In [6]:
display(atc.isna().sum())
display(benzo.isna().sum())
display(trolley.isna().sum())

YEAR_MONTH                                             0
ATC Class Category                                     0
ATC Class Code                                      1680
Product Category                                    1680
Prescribing Frequency                               1800
Prescribing Frequency Percentage of Scheme Total    1800
Ingredient Cost                                     1800
Ingredient Cost Percentage of Scheme Total          1800
Ingredient Cost Percentage of Scheme Total.1        1680
dtype: int64

Region                       0
Local Health Office (LHO)    0
YEAR_MONTH                   0
ATC Class                    0
Number of Patients           0
Number of Prescriptions      0
Prescribing Frequency        0
Igredient Cost (€)           0
Total Cost (€)               0
dtype: int64

YEAR_MONTH               0
Monthly_Trolley_Total    0
Monthly_Ward_Total       0
dtype: int64

In [8]:
atc[atc["Prescribing Frequency"].isna()].head(20)

,YEAR_MONTH,ATC Class Category,ATC Class Code,Product Category,Prescribing Frequency,Prescribing Frequency Percentage of Scheme Total,Ingredient Cost,Ingredient Cost Percentage of Scheme Total,Ingredient Cost Percentage of Scheme Total.1
12,201601,Alimentary Tract and Metabolism,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,201601,Antiinfectives For Systemic Use,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,201601,Antineoplastic and Immunomodulating Agents,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,201601,Antiparasitic Products Insecticides and Repell...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,201601,Blood and Blood Forming Organs,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,201601,Cardiovascular System,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,201601,Dermatologicals,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,201601,Genito Urinary System and Sex Hormones,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,201601,Musculo-Skeletal System,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,201601,Nervous System,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,201601,Respiratory System,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,201601,Sensory Organs,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,201601,Systemic Hormonal Preparations Excl. Sex Hormo...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
89,201601,Various,V07,All Other Non-Therapeutic Products,NaN,NaN,NaN,NaN,4.25
95,201601,Various,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109,201602,Alimentary Tract and Metabolism,NaN,NaN,NaN,NaN,NaN,NaN,NaN
114,201602,Antiinfectives For Systemic Use,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118,201602,Antineoplastic and Immunomodulating Agents,NaN,NaN,NaN,NaN,NaN,NaN,NaN
122,201602,Antiparasitic Products Insecticides and Repell...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
126,201602,Blood and Blood Forming Organs,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
atc_clean = atc[atc["Prescribing Frequency"].notna()].copy()
atc_clean.shape

(9688, 9)

In [12]:
atc_clean["YEAR_MONTH"] = pd.to_datetime(
    atc_clean["YEAR_MONTH"].astype(str),
    format="%Y%m"
)

atc_clean["YEAR_MONTH"].head()

0   2016-01-01
1   2016-01-01
2   2016-01-01
3   2016-01-01
4   2016-01-01
Name: YEAR_MONTH, dtype: datetime64[ns]

In [16]:
benzo["YEAR_MONTH"] = pd.to_datetime(
    benzo["YEAR_MONTH"].astype(str),
    format="%Y%m"
)

benzo["YEAR_MONTH"].head()

0   2018-01-01
1   2018-01-01
2   2018-01-01
3   2018-01-01
4   2018-01-01
Name: YEAR_MONTH, dtype: datetime64[ns]

In [22]:
trolley["YEAR_MONTH"] = pd.to_datetime(
    trolley["YEAR_MONTH"].astype(str),
    format="%Y%m"
)

trolley["YEAR_MONTH"].head()

0   2016-01-01
1   2016-02-01
2   2016-03-01
3   2016-04-01
4   2016-05-01
Name: YEAR_MONTH, dtype: datetime64[ns]

In [23]:
print("ATC:", atc_clean["YEAR_MONTH"].min(), "to", atc_clean["YEAR_MONTH"].max())
print("Benzo:", benzo["YEAR_MONTH"].min(), "to", benzo["YEAR_MONTH"].max())
print("Trolley:", trolley["YEAR_MONTH"].min(), "to", trolley["YEAR_MONTH"].max())

ATC: 2016-01-01 00:00:00 to 2025-12-01 00:00:00
Benzo: 2018-01-01 00:00:00 to 2025-12-01 00:00:00
Trolley: 2016-01-01 00:00:00 to 2026-03-01 00:00:00

In [25]:
atc_clean[["ATC Class Category", "ATC Class Code", "Product Category", "Prescribing Frequency"]].head(30)

,ATC Class Category,ATC Class Code,Product Category,Prescribing Frequency
0,Alimentary Tract and Metabolism,A01,Stomatological Preparations,6774.0
1,Alimentary Tract and Metabolism,A02,Drugs For Acid Related Disorders,322537.0
2,Alimentary Tract and Metabolism,A03,Drugs For Functional Gastrointestinal Disorders,36323.0
3,Alimentary Tract and Metabolism,A04,Antiemetics and Antinauseants,2940.0
4,Alimentary Tract and Metabolism,A05,Bile and Liver Therapy,1543.0
5,Alimentary Tract and Metabolism,A06,Laxatives,70781.0
6,Alimentary Tract and Metabolism,A07,Antidiarrheals Intestinal Antiinflammatory/Ant...,21874.0
7,Alimentary Tract and Metabolism,A09,Digestives Incl. Enzymes,1753.0
8,Alimentary Tract and Metabolism,A10,Drugs Used In Diabetes,61839.0
9,Alimentary Tract and Metabolism,A11,Vitamins,30409.0
10,Alimentary Tract and Metabolism,A12,Mineral Supplements,95692.0
11,Alimentary Tract and Metabolism,A14,Anabolic Agents For Systemic Use,14.0
13,Antiinfectives For Systemic Use,J01,Antibacterials For Systemic Use,266406.0
14,Antiinfectives For Systemic Use,J02,Antimycotics For Systemic Use,8944.0
15,Antiinfectives For Systemic Use,J04,Antimycobacterials,645.0
16,Antiinfectives For Systemic Use,J05,Antivirals For Systemic Use,4934.0
18,Antineoplastic and Immunomodulating Agents,L01,Antineoplastic Agents,3158.0
19,Antineoplastic and Immunomodulating Agents,L02,Endocrine Therapy,8773.0
20,Antineoplastic and Immunomodulating Agents,L04,Immunosuppressive Agents,14759.0
22,Antiparasitic Products Insecticides and Repell...,P01,Antiprotozoals,8982.0
23,Antiparasitic Products Insecticides and Repell...,P02,Anthelmintics,836.0
24,Antiparasitic Products Insecticides and Repell...,P03,Ectoparasiticides Incl. Scabicides Insecticide...,1830.0
26,Blood and Blood Forming Organs,B01,Antithrombotic Agents,274844.0
27,Blood and Blood Forming Organs,B02,Antihemorrhagics,1391.0
28,Blood and Blood Forming Organs,B03,Antianemic Preparations,76233.0
30,Cardiovascular System,C01,Cardiac Therapy,52262.0
31,Cardiovascular System,C02,Antihypertensives,17256.0
32,Cardiovascular System,C03,Diuretics,106767.0
33,Cardiovascular System,C04,Peripheral Vasodilators,2730.0
34,Cardiovascular System,C05,Vasoprotectives,9926.0

In [26]:
atc_monthly_wide = atc_clean.pivot_table(
    index="YEAR_MONTH",
    columns="ATC Class Code",
    values="Prescribing Frequency",
    aggfunc="sum"
).reset_index()

atc_monthly_wide.head()

ATC Class Code,YEAR_MONTH,A01,A02,A03,A04,A05,A06,A07,A08,A09,...,S03,V01,V03,V04,V06,V07 1,V07 2,V07 3,V07 4,V07 5
0,2016-01-01,6774.0,322537.0,36323.0,2940.0,1543.0,70781.0,21874.0,NaN,1753.0,...,5613.0,56.0,1843.0,18586.0,46856.0,19127.0,9567.0,14874.0,2354.0,5266.0
1,2016-02-01,7173.0,317940.0,35610.0,2969.0,1510.0,71801.0,21613.0,2.0,1712.0,...,5772.0,70.0,1849.0,18505.0,47634.0,19260.0,9422.0,14601.0,2429.0,5281.0
2,2016-03-01,7477.0,331828.0,37015.0,3174.0,1611.0,72708.0,22847.0,NaN,1779.0,...,5760.0,78.0,1947.0,18569.0,48483.0,19855.0,9802.0,14333.0,2076.0,5257.0
3,2016-04-01,7282.0,330883.0,36708.0,3161.0,1597.0,73287.0,23338.0,NaN,1808.0,...,5753.0,94.0,1957.0,17339.0,48494.0,20268.0,10055.0,13870.0,2241.0,5149.0
4,2016-05-01,7102.0,325370.0,35843.0,3096.0,1555.0,72389.0,23325.0,NaN,1744.0,...,5583.0,84.0,1889.0,16259.0,48695.0,20399.0,9873.0,13280.0,2597.0,5001.0

In [28]:
atc_monthly_wide.columns.name = None
atc_monthly_wide.head()

,YEAR_MONTH,A01,A02,A03,A04,A05,A06,A07,A08,A09,...,S03,V01,V03,V04,V06,V07 1,V07 2,V07 3,V07 4,V07 5
0,2016-01-01,6774.0,322537.0,36323.0,2940.0,1543.0,70781.0,21874.0,NaN,1753.0,...,5613.0,56.0,1843.0,18586.0,46856.0,19127.0,9567.0,14874.0,2354.0,5266.0
1,2016-02-01,7173.0,317940.0,35610.0,2969.0,1510.0,71801.0,21613.0,2.0,1712.0,...,5772.0,70.0,1849.0,18505.0,47634.0,19260.0,9422.0,14601.0,2429.0,5281.0
2,2016-03-01,7477.0,331828.0,37015.0,3174.0,1611.0,72708.0,22847.0,NaN,1779.0,...,5760.0,78.0,1947.0,18569.0,48483.0,19855.0,9802.0,14333.0,2076.0,5257.0
3,2016-04-01,7282.0,330883.0,36708.0,3161.0,1597.0,73287.0,23338.0,NaN,1808.0,...,5753.0,94.0,1957.0,17339.0,48494.0,20268.0,10055.0,13870.0,2241.0,5149.0
4,2016-05-01,7102.0,325370.0,35843.0,3096.0,1555.0,72389.0,23325.0,NaN,1744.0,...,5583.0,84.0,1889.0,16259.0,48695.0,20399.0,9873.0,13280.0,2597.0,5001.0

In [ ]:
master_atc_trolley = trolley.merge(
    atc_monthly_wide,
    on="YEAR_MONTH",
    how="inner"
)
master_atc_trolley.shape

(120, 89)

In [32]:
master_atc_trolley.head()

,YEAR_MONTH,Monthly_Trolley_Total,Monthly_Ward_Total,A01,A02,A03,A04,A05,A06,A07,...,S03,V01,V03,V04,V06,V07 1,V07 2,V07 3,V07 4,V07 5
0,2016-01-01,7537,1808,6774.0,322537.0,36323.0,2940.0,1543.0,70781.0,21874.0,...,5613.0,56.0,1843.0,18586.0,46856.0,19127.0,9567.0,14874.0,2354.0,5266.0
1,2016-02-01,6825,2060,7173.0,317940.0,35610.0,2969.0,1510.0,71801.0,21613.0,...,5772.0,70.0,1849.0,18505.0,47634.0,19260.0,9422.0,14601.0,2429.0,5281.0
2,2016-03-01,7018,2363,7477.0,331828.0,37015.0,3174.0,1611.0,72708.0,22847.0,...,5760.0,78.0,1947.0,18569.0,48483.0,19855.0,9802.0,14333.0,2076.0,5257.0
3,2016-04-01,6211,1934,7282.0,330883.0,36708.0,3161.0,1597.0,73287.0,23338.0,...,5753.0,94.0,1957.0,17339.0,48494.0,20268.0,10055.0,13870.0,2241.0,5149.0
4,2016-05-01,5117,1510,7102.0,325370.0,35843.0,3096.0,1555.0,72389.0,23325.0,...,5583.0,84.0,1889.0,16259.0,48695.0,20399.0,9873.0,13280.0,2597.0,5001.0

In [33]:
master_atc_trolley.tail()

,YEAR_MONTH,Monthly_Trolley_Total,Monthly_Ward_Total,A01,A02,A03,A04,A05,A06,A07,...,S03,V01,V03,V04,V06,V07 1,V07 2,V07 3,V07 4,V07 5
115,2025-08-01,5680,2824,49485.0,403036.0,22469.0,4964.0,3036.0,82596.0,25259.0,...,4839.0,178.0,1791.0,10424.0,62852.0,41238.0,17003.0,8709.0,4516.0,3266.0
116,2025-09-01,6274,3493,60109.0,410957.0,22831.0,5188.0,3062.0,85577.0,25685.0,...,5115.0,157.0,1793.0,10505.0,63707.0,41975.0,17333.0,9608.0,4734.0,3702.0
117,2025-10-01,6404,3239,63881.0,416718.0,22979.0,5300.0,3089.0,86235.0,25650.0,...,4776.0,194.0,1849.0,10413.0,63694.0,42294.0,17515.0,9748.0,4779.0,3757.0
118,2025-11-01,6057,2979,64389.0,400293.0,21564.0,4997.0,2986.0,83184.0,24390.0,...,4341.0,168.0,1761.0,10073.0,60999.0,40824.0,17151.0,9368.0,4366.0,3263.0
119,2025-12-01,5943,2604,93082.0,435140.0,23568.0,5632.0,3247.0,88877.0,27012.0,...,3404.0,188.0,1908.0,10414.0,64707.0,44394.0,18595.0,10273.0,3766.0,3650.0

In [34]:
master_atc_trolley.isna().sum().sort_values(ascending=False).head(20)

L03    119
J07    116
A08    115
R02    105
A16     85
D04     70
B05     20
H04      1
D03      1
M05      0
N03      0
N02      0
N01      0
M09      0
M03      0
M04      0
N05      0
M02      0
M01      0
L04      0
dtype: int64

In [36]:
atc_cols_to_drop = ["L03", "J07", "A08", "R02", "A16", "D04"]

master_atc_trolley_clean = master_atc_trolley.drop(columns=atc_cols_to_drop)

master_atc_trolley_clean = master_atc_trolley_clean.fillna(0)

master_atc_trolley_clean.shape

(120, 83)

In [37]:
master_atc_trolley_clean.isna().sum().sum()

np.int64(0)

In [38]:
master_atc_trolley_clean.to_csv(
    "../data/processed/master_atc_trolley_clean.csv",
    index=False
)

In [39]:
benzo.head()

,Region,Local Health Office (LHO),YEAR_MONTH,ATC Class,Number of Patients,Number of Prescriptions,Prescribing Frequency,Igredient Cost (€),Total Cost (€)
0,HSE Dublin and Midlands,Dublin South City,2018-01-01,N03AE01,99,123,123,256.71,1117.09
1,HSE Dublin and Midlands,Dublin South City,2018-01-01,N05BA01,1098,1442,1501,1952.57,13240.98
2,HSE Dublin and Midlands,Dublin South City,2018-01-01,N05BA02,61,88,94,215.77,831.16
3,HSE Dublin and Midlands,Dublin South City,2018-01-01,N05BA06,72,90,90,116.00,616.14
4,HSE Dublin and Midlands,Dublin South City,2018-01-01,N05BA08,134,149,149,485.28,1307.51

In [ ]:
benzo_monthly_wide = benzo.pivot_table(
    index="YEAR_MONTH",
    columns="ATC Class",
    values="Prescribing Frequency",
    aggfunc="sum"
).reset_index()

benzo_monthly_wide.columns.name = None

benzo_monthly_wide.head()

ATC Class
N05CF02    3047
N05CD08    3046
N05BA12    3046
N05BA01    3046
N05CF01    3046
N03AE01    3045
N05BA08    3045
N05CD07    3045
N05BA06    3044
N05BA09    3044
N05CD05    3044
N05BA02    3043
N05CD01    3037
N05CD02    2132
N05BA11    2059
N05CD06    1270
N05BA05    1080
N05CD03       1
Name: count, dtype: int64

In [41]:
benzo_freq_wide = benzo.pivot_table(
    index="YEAR_MONTH",
    columns="ATC Class",
    values="Prescribing Frequency",
    aggfunc="sum"
).add_prefix("BENZO_FREQ_").reset_index()

benzo_patients_wide = benzo.pivot_table(
    index="YEAR_MONTH",
    columns="ATC Class",
    values="Number of Patients",
    aggfunc="sum"
).add_prefix("BENZO_PATIENTS_").reset_index()

In [42]:
benzo_monthly_wide = (
    benzo_freq_wide
    .merge(benzo_patients_wide, on="YEAR_MONTH", how="inner")
)

benzo_monthly_wide.head()

ATC Class,YEAR_MONTH,BENZO_FREQ_N03AE01,BENZO_FREQ_N05BA01,BENZO_FREQ_N05BA02,BENZO_FREQ_N05BA05,BENZO_FREQ_N05BA06,BENZO_FREQ_N05BA08,BENZO_FREQ_N05BA09,BENZO_FREQ_N05BA11,BENZO_FREQ_N05BA12,...,BENZO_PATIENTS_N05BA12,BENZO_PATIENTS_N05CD01,BENZO_PATIENTS_N05CD02,BENZO_PATIENTS_N05CD03,BENZO_PATIENTS_N05CD05,BENZO_PATIENTS_N05CD06,BENZO_PATIENTS_N05CD07,BENZO_PATIENTS_N05CD08,BENZO_PATIENTS_N05CF01,BENZO_PATIENTS_N05CF02
0,2018-01-01,7319.0,36919.0,2568.0,18.0,3720.0,7418.0,1343.0,1280.0,34085.0,...,28068.0,7980.0,1230.0,NaN,5717.0,3093.0,6421.0,2029.0,42837.0,34878.0
1,2018-02-01,6643.0,33333.0,2140.0,18.0,3387.0,6905.0,1207.0,1199.0,30757.0,...,26592.0,7646.0,1164.0,NaN,5429.0,2991.0,6089.0,1709.0,40471.0,32592.0
2,2018-03-01,7147.0,35477.0,2220.0,14.0,3568.0,7226.0,1265.0,1254.0,32788.0,...,27507.0,7800.0,1203.0,NaN,5504.0,3032.0,6157.0,1788.0,41448.0,33567.0
3,2018-04-01,7002.0,34545.0,2336.0,17.0,3519.0,7052.0,1237.0,1239.0,32093.0,...,27484.0,7656.0,1181.0,NaN,5470.0,2928.0,6075.0,1800.0,40877.0,32983.0
4,2018-05-01,7342.0,36448.0,2341.0,20.0,3659.0,7328.0,1290.0,1280.0,34184.0,...,28275.0,7707.0,1175.0,NaN,5510.0,3019.0,6122.0,1824.0,41309.0,33459.0

In [43]:
benzo_missing = benzo_monthly_wide.isna().sum().sort_values(ascending=False)
benzo_missing[benzo_missing > 0]

ATC Class
BENZO_FREQ_N05CD03        95
BENZO_PATIENTS_N05CD03    95
BENZO_FREQ_N05CD06        25
BENZO_PATIENTS_N05CD06    25
BENZO_PATIENTS_N05CD02    14
BENZO_FREQ_N05CD02        14
BENZO_FREQ_N05BA11        13
BENZO_PATIENTS_N05BA11    13
BENZO_PATIENTS_N05BA05     1
BENZO_FREQ_N05BA05         1
dtype: int64

In [44]:
benzo_cols_to_drop = benzo_missing[benzo_missing > 20].index.tolist()
benzo_monthly_clean = benzo_monthly_wide.drop(columns=benzo_cols_to_drop)
benzo_monthly_clean = benzo_monthly_clean.fillna(0)

In [45]:
benzo_monthly_clean.shape

(96, 33)

In [ ]:
benzo_monthly_clean.isna().sum().sum()

np.int64(0)

In [47]:
master_benzo_trolley_clean = trolley.merge(
    benzo_monthly_clean,
    on="YEAR_MONTH",
    how="inner"
)

master_benzo_trolley_clean.shape

(96, 35)

In [48]:
display(master_benzo_trolley_clean.head())
display(master_benzo_trolley_clean.tail())

,YEAR_MONTH,Monthly_Trolley_Total,Monthly_Ward_Total,BENZO_FREQ_N03AE01,BENZO_FREQ_N05BA01,BENZO_FREQ_N05BA02,BENZO_FREQ_N05BA05,BENZO_FREQ_N05BA06,BENZO_FREQ_N05BA08,BENZO_FREQ_N05BA09,...,BENZO_PATIENTS_N05BA09,BENZO_PATIENTS_N05BA11,BENZO_PATIENTS_N05BA12,BENZO_PATIENTS_N05CD01,BENZO_PATIENTS_N05CD02,BENZO_PATIENTS_N05CD05,BENZO_PATIENTS_N05CD07,BENZO_PATIENTS_N05CD08,BENZO_PATIENTS_N05CF01,BENZO_PATIENTS_N05CF02
0,2018-01-01,9104,3291,7319.0,36919.0,2568.0,18.0,3720.0,7418.0,1343.0,...,1133.0,1137.0,28068.0,7980.0,1230.0,5717.0,6421.0,2029.0,42837.0,34878.0
1,2018-02-01,8032,2982,6643.0,33333.0,2140.0,18.0,3387.0,6905.0,1207.0,...,1098.0,1115.0,26592.0,7646.0,1164.0,5429.0,6089.0,1709.0,40471.0,32592.0
2,2018-03-01,7611,3083,7147.0,35477.0,2220.0,14.0,3568.0,7226.0,1265.0,...,1094.0,1127.0,27507.0,7800.0,1203.0,5504.0,6157.0,1788.0,41448.0,33567.0
3,2018-04-01,6586,2847,7002.0,34545.0,2336.0,17.0,3519.0,7052.0,1237.0,...,1092.0,1120.0,27484.0,7656.0,1181.0,5470.0,6075.0,1800.0,40877.0,32983.0
4,2018-05-01,6393,2790,7342.0,36448.0,2341.0,20.0,3659.0,7328.0,1290.0,...,1094.0,1134.0,28275.0,7707.0,1175.0,5510.0,6122.0,1824.0,41309.0,33459.0

,YEAR_MONTH,Monthly_Trolley_Total,Monthly_Ward_Total,BENZO_FREQ_N03AE01,BENZO_FREQ_N05BA01,BENZO_FREQ_N05BA02,BENZO_FREQ_N05BA05,BENZO_FREQ_N05BA06,BENZO_FREQ_N05BA08,BENZO_FREQ_N05BA09,...,BENZO_PATIENTS_N05BA09,BENZO_PATIENTS_N05BA11,BENZO_PATIENTS_N05BA12,BENZO_PATIENTS_N05CD01,BENZO_PATIENTS_N05CD02,BENZO_PATIENTS_N05CD05,BENZO_PATIENTS_N05CD07,BENZO_PATIENTS_N05CD08,BENZO_PATIENTS_N05CF01,BENZO_PATIENTS_N05CF02
91,2025-08-01,5680,2824,5880.0,35817.0,1849.0,22.0,3489.0,4440.0,1345.0,...,1158.0,0.0,25289.0,1427.0,0.0,4221.0,3888.0,2327.0,40443.0,31775.0
92,2025-09-01,6274,3493,5970.0,36263.0,1788.0,16.0,3656.0,4458.0,1346.0,...,1156.0,0.0,26014.0,1456.0,0.0,4239.0,3900.0,2442.0,40537.0,32013.0
93,2025-10-01,6404,3239,6724.0,33123.0,2824.0,26.0,4172.0,5215.0,1391.0,...,1197.0,0.0,27896.0,1509.0,0.0,4232.0,3936.0,2426.0,40967.0,32106.0
94,2025-11-01,6057,2979,6068.0,32703.0,2073.0,24.0,3687.0,4602.0,1314.0,...,1158.0,0.0,25917.0,1437.0,1.0,4194.0,3799.0,2413.0,40145.0,31687.0
95,2025-12-01,5943,2604,6485.0,35671.0,1859.0,26.0,3952.0,4953.0,1434.0,...,1177.0,0.0,26356.0,1508.0,0.0,4196.0,3854.0,2756.0,40848.0,32270.0

In [49]:
master_benzo_trolley_clean.to_csv(
    "../data/processed/master_benzo_trolley_clean.csv",
    index=False
)

In [52]:
master_benzo_trolley_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96 entries, 0 to 95
Data columns (total 35 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   YEAR_MONTH              96 non-null     datetime64[ns]
 1   Monthly_Trolley_Total   96 non-null     int64
 2   Monthly_Ward_Total      96 non-null     int64
 3   BENZO_FREQ_N03AE01      96 non-null     float64
 4   BENZO_FREQ_N05BA01      96 non-null     float64
 5   BENZO_FREQ_N05BA02      96 non-null     float64
 6   BENZO_FREQ_N05BA05      96 non-null     float64
 7   BENZO_FREQ_N05BA06      96 non-null     float64
 8   BENZO_FREQ_N05BA08      96 non-null     float64
 9   BENZO_FREQ_N05BA09      96 non-null     float64
 10  BENZO_FREQ_N05BA11      96 non-null     float64
 11  BENZO_FREQ_N05BA12      96 non-null     float64
 12  BENZO_FREQ_N05CD01      96 non-null     float64
 13  BENZO_FREQ_N05CD02      96 non-null     float64
 14  BENZO_FREQ_N05CD05      96 non-null     float64
 15  BENZO_FREQ_N05CD07      96 non-null     float64
 16  BENZO_FREQ_N05CD08      96 non-null     float64
 17  BENZO_FREQ_N05CF01      96 non-null     float64
 18  BENZO_FREQ_N05CF02      96 non-null     float64
 19  BENZO_PATIENTS_N03AE01  96 non-null     float64
 20  BENZO_PATIENTS_N05BA01  96 non-null     float64
 21  BENZO_PATIENTS_N05BA02  96 non-null     float64
 22  BENZO_PATIENTS_N05BA05  96 non-null     float64
 23  BENZO_PATIENTS_N05BA06  96 non-null     float64
 24  BENZO_PATIENTS_N05BA08  96 non-null     float64
 25  BENZO_PATIENTS_N05BA09  96 non-null     float64
 26  BENZO_PATIENTS_N05BA11  96 non-null     float64
 27  BENZO_PATIENTS_N05BA12  96 non-null     float64
 28  BENZO_PATIENTS_N05CD01  96 non-null     float64
 29  BENZO_PATIENTS_N05CD02  96 non-null     float64
 30  BENZO_PATIENTS_N05CD05  96 non-null     float64
 31  BENZO_PATIENTS_N05CD07  96 non-null     float64
 32  BENZO_PATIENTS_N05CD08  96 non-null     float64
 33  BENZO_PATIENTS_N05CF01  96 non-null     float64
 34  BENZO_PATIENTS_N05CF02  96 non-null     float64
dtypes: datetime64[ns](1), float64(32), int64(2)
memory usage: 26.4 KB

In [53]:
print(master_atc_trolley_clean.shape)
print(master_benzo_trolley_clean.shape)

print(master_atc_trolley_clean["YEAR_MONTH"].min(), master_atc_trolley_clean["YEAR_MONTH"].max())
print(master_benzo_trolley_clean["YEAR_MONTH"].min(), master_benzo_trolley_clean["YEAR_MONTH"].max())

print(master_atc_trolley_clean.isna().sum().sum())
print(master_benzo_trolley_clean.isna().sum().sum())

(120, 83)
(96, 35)
2016-01-01 00:00:00 2025-12-01 00:00:00
2018-01-01 00:00:00 2025-12-01 00:00:00
0
0